apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  namespace: load-gen
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      initContainers:
      - name: setup
        image: public.ecr.aws/aws-containers/retail-store-sample-utils:load-gen.1.2.1
        command: ["bash"]
        args: ["-c", "cp /artillery/* /scripts"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      containers:
      - name: artillery
        image: artilleryio/artillery:2.0.22
        args:
        - "run"
        - "-t"
        - "http://ui.ui.svc.cluster.local"
        - "--overrides"
        - '{"config":{"phases":[{"duration":600,"arrivalRate":20}]}}'
        - "/scripts/scenario.yml"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        emptyDir: {}

